=== Poorwak/mod-1/XML/email.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

		<xs:element name="To" type="xs:string"/>
		<xs:element name ="From" type="xs:string"/>
		<xs:element name ="CC" type="xs:string"/>
		<xs:element name ="BCC" type="xs:string"/>
		<xs:element name ="Subject" type="xs:string"/>
		<xs:element name="Body" type="xs:string"/>
		<xs:element name="Email" type="emType"/>
		
		<xs:complexType name="emType">
			<xs:sequence>	
				<xs:element ref="To"/>
				<xs:element ref="From"/>
				<xs:element ref="CC"/>
				<xs:element ref="BCC"/>
				<xs:element ref="Subject"/>
				<xs:element ref="Body"/>
			</xs:sequence>
		</xs:complexType>
		
		<xs:element name="eDetails" type="elistType"/>
		<xs:complexType name="elistType">
			<xs:sequence>
				<xs:element ref="Email" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
</xs:schema>

=== Poorwak/mod-1/XML/email.xml
<?xml version="1.0" ?>
<eDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="email.xsd">
<Email>
		<To>xyz@gmail.com</To>
		<From>abc@gmail.com</From>
		<CC>pqr@gmail.com</CC>
		<BCC>def@gmail.com</BCC>
		<Subject>Learning Modules of XML</Subject>
		<Body>XML is the EXtensible Markup Language.</Body>
</Email>
</eDetails>
